// USER
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

export const ME_REQUEST = 'ME_REQUEST'
export const ME_SUCCESS = 'ME_SUCCESS'
export const ME_FAILURE = 'ME_FAILURE'

export const EDIT_ME_REQUEST = 'EDIT_ME_REQUEST'
export const EDIT_ME_SUCCESS = 'EDIT_ME_SUCCESS'
export const EDIT_ME_FAILURE = 'EDIT_ME_FAILURE'

export const NEW_ME_REQUEST = 'NEW_ME_REQUEST'
export const NEW_ME_SUCCESS = 'NEW_ME_SUCCESS'
export const NEW_ME_FAILURE = 'NEW_ME_FAILURE'

export const AVATAR_REQUEST = 'AVATAR_REQUEST'
export const AVATAR_SUCCESS = 'AVATAR_SUCCESS'
export const AVATAR_FAILURE = 'AVATAR_FAILURE'

// DIARY
export const DIARY_REQUEST = 'DIARY_REQUEST'
export const DIARY_SUCCESS = 'DIARY_SUCCESS'
export const DIARY_FAILURE = 'DIARY_FAILURE'

export const EDIT_DIARY_REQUEST = 'EDIT_DIARY_REQUEST'
export const EDIT_DIARY_SUCCESS = 'EDIT_DIARY_SUCCESS'
export const EDIT_DIARY_FAILURE = 'EDIT_DIARY_FAILURE'

export const NEW_DIARY_REQUEST = 'NEW_DIARY_REQUEST'
export const NEW_DIARY_SUCCESS = 'NEW_DIARY_SUCCESS'
export const NEW_DIARY_FAILURE = 'NEW_DIARY_FAILURE'

export const DELETE_DIARY_REQUEST = 'DELETE_DIARY_REQUEST'
export const DELETE_DIARY_SUCCESS = 'DELETE_DIARY_SUCCESS'
export const DELETE_DIARY_FAILURE = 'DELETE_DIARY_FAILURE'

export const COUNT_REQUEST = 'COUNT_REQUEST'
export const COUNT_SUCCESS = 'COUNT_SUCCESS'
export const COUNT_FAILURE = 'COUNT_FAILURE'